### PR TITLE
Update README.md to remove build server reference

### PR DESCRIPTION
**Pull request by lps-rocks**
Removed official build server reference, added unofficial reference to rom-o-matic.dev

### CODE REVIEW

**Comment by MaxPeal** [comment]
@lps-rocks please enable issues in youre fork

**Comment by MaxPeal** [comment]
@lps-rocks youre host dont compile:
URL https://rom-o-matic.dev/build.fcgi?BINARY=ipxe.iso&BINDIR=bin&REVISION=master&DEBUG=&EMBED.00script.ipxe=&

Build failed:

Could not dup tarfh: Bad file descriptor


Build log:
Path: 
Parameters: 
  BINARY = ipxe.iso
  BINDIR = bin
  DEBUG = 
  EMBED.00script.ipxe = 
  REVISION = master
Binary: ipxe.iso
Binary directory: bin
Revision: master
Canonicalising revision master...
Canonical revision: 98d49e460a27f74212aab2d6b5eef1143c7a8e37
Creating temporary directories...
Temporary git directory: /tmp/ipxe/build/ipxe-build-InipJd
Temporary working tree: /tmp/ipxe/build/ipxe-build-WHqnht
Cloning git tree from /tmp/ipxe/source/.git...
Finding closest cached binaries for 98d49e460a27f74212aab2d6b5eef1143c7a8e37...
Found cached binaries in ipxe-build/cached/bin/98d49e460a27f74212aab2d6b5eef1143c7a8e37.gz at distance 0
Opening binary tarball /tmp/ipxe/cache/98d49e460a27f74212aab2d6b5eef1143c7a8e37-bin.tar.gz...
Opened binary tarball /tmp/ipxe/cache/98d49e460a27f74212aab2d6b5eef1143c7a8e37-bin.tar.gz...
Checking out revision 98d49e460a27f74212aab2d6b5eef1143c7a8e37...
Identifying timestamp for commit 98d49e460a27f74212aab2d6b5eef1143c7a8e37...
Setting timestamps to Tue Jul  7 13:08:05 2020...
Unpacking binary tarball /tmp/ipxe/cache/98d49e460a27f74212aab2d6b5eef1143c7a8e37-bin.tar.gz...
Could not dup tarfh: Bad file descriptor
Filehandle STDIN reopened as STDOUT only for output at /var/www/rom-o-matic/build.fcgi line 749.

**Comment by lps-rocks** [comment]
@MaxPeal - I've enabled issues on my fork and also fixed the build issue. I've added a monitor to ensure that builds are working properly.

**Comment by xbgmsharp** [comment]
Fix with 4360b732bedff7a710a6b76c7ccc19ef3ccc17bd

**Pull request closed without merging**
